name: Trunk Check

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
